### ISSUE TITLE
Double click on Location search bar

### ISSUE THREAD

**Issue by tucotuco** [aescobarr/GeoPick#86]
This is extremely minor. If I happen to double click on the Location search bar, the map will zoom in one level. This is the behavior expected when the cursor is over the map, but can it be avoided when it is over the Location search bar. The situation in which is usually arises is double-clicking on a word in the Location search bar in order to highlight it.

**Comment by arnaldmarcer** [comment]
Solved @tucotuco , in version 1.0.1
